require:
  - rubocop-performance
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3

# Until fix of
# https://github.com/rubocop/rubocop-rspec/issues/1823
RSpec/Rails/HaveHttpStatus:
  Enabled: false
